### ISSUE TITLE
Override flags with environment variables

### ISSUE THREAD

**Issue by TymekDev** [szymanskir/featureflag#37]
Use case: I am releasing a new feature. I want it enabled in dev, in tests, but not in prod. When the day comes, I want to enable it on prod too without redeploying the application.

What would be the best way to approach this?

Currently, I am going to use something like:
```
default:
  feature_foo: !expr featureflag::create_bool_feature_flag(value = TRUE)
production:
  feature_foo: !expr featureflag::create_bool_feature_flag(value = isTRUE(as.logical(Sys.getenv("FEATURE_FOO", "FALSE"))))
```
But then it's quite verbose.

**Comment by szymanskir** [comment]
Noting down the idea from our chat.

Provide a feature flag based on an environment variable

```r
foo_feature_flag <- create_env_feature_flag(env_var_name = "FEATURE_FOO")

# if FEATURE_FOO does not exist
is_enabled(foo_feature_flag)
# FALSE

# If FEATURE_FOO exists
withr::with_envvar(list(FEATURE_FOO = "true"), {
  is_enabled(foo_feature_flag)
  # TRUE
})

# If FEATURE_FOO has a typo
withr::with_envvar(list(FEATURE_FOO = "trEu"), {
  is_enabled(foo_feature_flag)
  # FALSE and show a warning
})
```

With that you could do 

```
default:
  feature_foo: !expr featureflag::create_bool_feature_flag(value = TRUE)
production:
  feature_foo: !expr featureflag::create_env_feature_flag(env_var_name = "FEATURE_FOO")
```
